# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # config.vm.box_check_update = false
    config.vm.synced_folder "./vagrant_data", "/vagrant_data"
  
    # Disable the default SSH key insertion
    config.ssh.insert_key = false
  
    config.vm.provider :virtualbox do |vb|
      vb.memory = "3072"
      vb.cpus = "2"
    end

    config.vm.define :master do |master|
      master.vm.box = "alvistack/ubuntu-22.04"
      master.vm.network "private_network", ip: "192.168.44.2"
  
      master.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        # Set up the hostnames and configure the hostname for this machine
        echo '192.168.44.2 master' >> /etc/hosts
        sudo hostnamectl set-hostname master
        # Enable password authentication for SSH
        sudo sed -e \"s/PasswordAuthentication no/PasswordAuthentication yes/\" /etc/ssh/sshd_config > /etc/ssh/sshd_config_tmp
        sudo mv /etc/ssh/sshd_config_tmp /etc/ssh/sshd_config
        sudo systemctl restart sshd.service
      SHELL
    end
  end
  