- name: "Setup Docker-Compose with Ansible"
  hosts: worker
  remote_user: vagrant
  vars:
    docker_remote_user: vagrant
  become: true
  tasks:
    - name: "Install Docker Prerequisite Package"
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum-utils
    - name: "Add Docker Repository"
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: "Install Docker Engine"
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: "Create docker Group"
      group:
        name: docker
        state: present
    - name: "Add User to docker Group"
      ansible.builtin.user:
        name: "{{ docker_remote_user }}"
        groups: docker
        append: true
      register: add_to_docker_group_result
    - name: Include Reset Connection Tasks
      ansible.builtin.include_tasks: reset-connection.yml
      when: add_to_docker_group_result.changed == true
    - name: "Start and Enable Docker Service"
      service:
        name: docker
        state: started
        enabled: yes
    - name: "Get uname -s"
      command: "uname -s"
      register: uname_s_result
    - name: "Get uname -m"
      command: "uname -m"
      register: uname_m_result
    - name: "Save Variables"
      set_fact:
        uname_s: "{{ uname_s_result.stdout }}"
        uname_m: "{{ uname_m_result.stdout }}"
    - name: "Download Docker-Compose"
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-{{ uname_s }}-{{ uname_m }}"
        dest: /usr/local/bin/docker-compose
    - name: "Give Executable Permission to Docker-Compose"
      file: dest=/usr/local/bin/docker-compose mode=+x
